baseURL = 'https://victim1307.github.io/new-crypto-learn/'
languageCode = 'en-us'
title = 'CryptoLearn'
[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false
    [[module.imports]]
        path = 'github.com/hugomods/images'
        disable = false
